CREATE OR REPLACE WAREHOUSE COMPUTE_WH
WITH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE RAW;

CREATE OR REPLACE SCHEMA RAW.OLIST_ECOMMERCE;